/**
 * ---------------------
 * 🚗🚦 Generated by nuxt-typed-router. Do not modify !
 * ---------------------
 * */

export const routerPagesNames = {
  about: "about" as const,
  index: "index" as const,
};

export type TypedRouteList = "about" | "index";
